[package]
name = "mrc"
version = "0.1.1"
edition = "2024"
rust-version = "1.85"
description = "Zero-copy, zero-allocation MRC-2014 file format reader/writer for Rust"
license = "MIT"
repository = "https://github.com/elemeng/mrc"
homepage = "https://github.com/elemeng/mrc"
documentation = "https://docs.rs/mrc"
keywords = ["mrc", "cryo-em", "cryo-ET", "microscopy", "scientific-computing"]
categories = ["science", "data-structures", "no-std", "memory-management"]
readme = "README.md"

[dependencies]
bytemuck = { version = "1.15", default-features = false, features = ["derive"] }
memmap2 = { version = "0.9", optional = true }
thiserror = { version = "2.0.16", default-features = false }
half = { version = "2.6", optional = true, default-features = false, features = [
    "bytemuck",
] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
half = "2.6.0"
tempfile = "3.8"

[[example]]
name = "test_real_mrc"

[[example]]
name = "test_all_features"

[[example]]
name = "validate"
path = "examples/validate.rs"

[[example]]
name = "generate_mrc_files"
path = "examples/generate_mrc_files.rs"

[[bench]]
name = "benchmark"
path = "test/benchmark.rs"
harness = false

[[bench]]
name = "performance"
path = "test/performance.rs"
harness = false

[features]
default = ["std", "mmap", "file", "f16"]
mmap = ["std", "dep:memmap2"]
file = ["std"]
std = []
f16 = []
